### PR TITLE
【gem】webpackerのgemを追加/Reactの利用準備

### PR DESCRIPTION
**Pull request by hiroaki514**
## PRの目的
Reactを使用するための準備としてwebpackerのgemを追加し、表示確認用の関連ファイルを追加しました。
またインストールに伴い一部設定ファイルの修正を行いました。

## 対象のissues
https://github.com/hiroaki514/BeeBits/issues/39

## 備考
ドラフト作成時点で、下記の変更を取り込んでいます。
[fix_user_registration](https://github.com/hiroaki514/BeeBits/tree/fix_user_registration)
[add_Timelines_controller](https://github.com/hiroaki514/BeeBits/tree/add_Timelines_controller)

### CODE REVIEW

**Comment by hiroaki514** [comment]
https://github.com/hiroaki514/BeeBits/issues/39

**Comment by hiroaki514** [comment]
【問題点】

- [ ] Timeline#indexに「This is the Timeline」の表示が確認できない
- [ ] デベロッパーツールにエラーが２件発生している(下部に記載)


bootstrap:83 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-proposal-private-methods' imported from /app/babel-virtual-resolve-base.js
    at new NodeError (:3000/app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:194:5)
    at packageResolve (:3000/app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:908:9)
    at moduleResolve (:3000/app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (:3000/app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (:3000/app/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (:3000/app/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (:3000/app/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (:3000/app/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPlugin (:3000/app/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (:3000/app/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at step (:3000/app/node_modules/gensync/index.js:261:32)
    at evaluateAsync (:3000/app/node_modules/gensync/index.js:291:5)
    at :3000/app/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (:3000/app/node_modules/gensync/index.js:43:15)
    at Function.all (:3000/app/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (:3000/app/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (:3000/app/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at :3000/app/node_modules/@babel/core/lib/gensync-utils/functional.js:39:27
    at Generator.next (<anonymous>)
    at mergeChainOpts (:3000/app/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (:3000/app/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (:3000/app/node_modules/@babel/core/lib/config/config-chain.js:191:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (:3000/app/node_modules/@babel/core/lib/config/config-chain.js:77:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (:3000/app/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadPartialConfig (:3000/app/node_modules/@babel/core/lib/config/partial.js:115:25)
    at loadPartialConfig.next (<anonymous>)
    at step (:3000/app/node_modules/gensync/index.js:269:25)
    at evaluateAsync (:3000/app/node_modules/gensync/index.js:291:5)
    at :3000/app/node_modules/gensync/index.js:93:9
    at new Promise (<anonymous>)
    at async (:3000/app/node_modules/gensync/index.js:92:14)
    at stopHiding - secret - don't use this - v1 (:3000/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at loadPartialConfigAsync (:3000/app/node_modules/@babel/core/lib/config/index.js:34:85)
    at Object.<anonymous> (:3000/app/node_modules/babel-loader/lib/index.js:126:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (:3000/app/node_modules/babel-loader/lib/index.js:3:103)
    at _next (:3000/app/node_modules/babel-loader/lib/index.js:4:194)
    at :3000/app/node_modules/babel-loader/lib/index.js:4:364
    at new Promise (<anonymous>)
    at ./app/javascript/packs/timeline.js (bootstrap:83:1)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1
./app/javascript/packs/timeline.js @ bootstrap:83
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
localhost/:1 Uncaught TypeError: Failed to resolve module specifier "application". Relative references must start with either "/", "./", or "../".

**Comment by yoshichiba** [comment]
@hiroaki514 
`webpacker`は2~3年前の古い技術で現在使っているサービスはないと思うので、使用しないでください！
（`webpacker`でReactを入れると確か大変だった記憶が、、、🤔）

Reactを導入する際は、ChatGPTではなくGoogle検索等で調べていただけますと！
（「Rails7 React」とかで検索すると良いかと）

**Comment by hiroaki514** [comment]
@yoshichiba 
そうなのですね！

「Rails7 React」で検索して再度やってみたいと思います。
こちら一旦クローズします！

**Pull request closed without merging**
